format_version: 10
pipelines:
  github-pipeline:
    group: DevOps
    label_template: "${COUNT}"
    parameters: 
      ENV: "dev"
    environment_variables:
      repository: https://github.com/saikrishnap123/GoCD.git 
    materials:
      git-repo:
        git: ${repository}
        branch: main
    stages:
      - build:
          jobs:
            build-job:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Hello, GoCD"
      
      - deploy:               # Stage 2
          approval: manual     # requires manual approval
          jobs:
            deploy-job:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "Hello ${ENV} environment "
                        