format_version: 10
pipelines:
  github-demo-pipeline:
    group: example
    label_template: "${COUNT}"
    materials:
      git-repo:
        git: https://github.com/saikrishnap123/GoCD.git
        branch: main
    stages:
      - build:
          jobs:
            build-job:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Hello, GoCD"
