format_version: 10

pipelines:
  github-demo-pipeline:
    group: DevOps
    materials:
      github-repo:
        type: git
        url: https://github.com/saikrishnap123/GoCD.git
        branch: main
    stages:
      - name: build-stage
        jobs:
          - name: build-job
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Hello, GoCD pipeline!"
